apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bWlyYW4= # base64 encoded 'miran'
  mongo-root-password: c2VjdXJlUGFzcw== # base64 encoded 'securePass'
