version: '3'
services:
  angular-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  angular-prod:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - "8080:80"
